const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const KEY="genevieve_v16_stock_recipe";
let state={stock:[],recipes:[],usage:[],shopping:[],filter:"all",currentRecipe:null,rules:{gluten:true,dairy:true,trace:true,housemate:true}};
const starter=[{name:"Chicken breast",location:"Fridge",qty:2,unit:"serves",yellow:1,red:.5,safety:"Green — Tracey safe",notes:"Plain. Check label."},{name:"Potato",location:"Pantry",qty:4,unit:"each",yellow:2,red:1,safety:"Green — Tracey safe",notes:""},{name:"Pumpkin",location:"Fridge",qty:500,unit:"g",yellow:200,red:50,safety:"Green — Tracey safe",notes:""},{name:"Soy milk",location:"Fridge",qty:600,unit:"ml",yellow:300,red:100,safety:"Amber — check / trace / uncertain",notes:"Check GF and may contain."},{name:"Gluten free plain flour",location:"Pantry",qty:500,unit:"g",yellow:200,red:50,safety:"Green — Tracey safe",notes:"GF label checked."}];
const blocked=["wheat","barley","rye","malt","gluten","ordinary oats","milk","cheese","cream","yoghurt","butter","whey","casein","milk solids"];
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch(e){} if(!state.stock.length){state.stock=starter;save()}}function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function go(id){$$(".screen").forEach(s=>s.classList.remove("active"));$("#"+id).classList.add("active");$$(".bottom button").forEach(b=>b.classList.toggle("active",b.dataset.screen===id));render();scrollTo({top:0,behavior:"smooth"})}
function colour(i){if(i.safety.startsWith("Red")||i.safety.startsWith("Housemate"))return"red";if(+i.qty<=+i.red)return"red";if(i.safety.startsWith("Amber")||+i.qty<=+i.yellow)return"amber";return"green"}
function risk(i){let c=colour(i);if(c==="red")return i.safety.startsWith("Red")||i.safety.startsWith("Housemate")?"Do not use":"Red stock alert";if(c==="amber")return i.safety.startsWith("Amber")?"Check first":"Yellow low stock";return"Ready"}
function render(){renderHome();renderStock();renderAlerts();renderShop();renderRecipes();$("#blockedTerms")&&($("#blockedTerms").innerHTML=blocked.map(x=>`<span>${x}</span>`).join(""))}
function renderHome(){let cols=state.stock.map(colour),r=cols.filter(x=>x==="red").length,a=cols.filter(x=>x==="amber").length;$("#statStock").textContent=state.stock.length;$("#statYellow").textContent=a;$("#statRed").textContent=r;$("#statShop").textContent=state.shopping.length;let orb=$("#homeOrb");orb.className="orb "+(r?"red":a?"amber":"green");orb.innerHTML=`<b>${r?"RED":a?"AMBER":"GREEN"}</b><span>${r?"Action needed":a?"Check stock":"Ready"}</span>`;$("#alertDot").style.display=(r||a)?"block":"none"}
function renderStock(){let el=$("#stockList");if(!el)return;let items=state.stock.filter(i=>state.filter==="all"||i.location===state.filter||colour(i)===state.filter);el.innerHTML=items.length?items.map(i=>{let idx=state.stock.indexOf(i),c=colour(i);return `<div class="item ${c}"><h4>${i.name}</h4><p>${i.location} • ${i.qty} ${i.unit} • ${risk(i)}</p><span class="tag ${c}">${c.toUpperCase()}</span><span class="tag">${i.safety}</span><p>${i.notes||""}</p><button onclick="adj(${idx},1)">+ Add</button> <button class="secondary" onclick="adj(${idx},-1)">− Use</button> <button class="secondary" onclick="delStock(${idx})">Delete</button></div>`}).join(""):"<p>No stock yet.</p>"}
function renderAlerts(){let html=state.stock.filter(i=>colour(i)!=="green").map(i=>{let c=colour(i);return `<div class="item ${c}"><h4>${i.name}</h4><p>${risk(i)} • ${i.qty} ${i.unit}</p><button onclick="addShop('${i.name.replace(/'/g,"")}','${c.toUpperCase()} alert')">Add</button> <button class="secondary" onclick="alert('Left off list for now')">Leave</button></div>`}).join("")||"<p>No alerts.</p>";if($("#alertList"))$("#alertList").innerHTML=html;if($("#autoShop"))$("#autoShop").innerHTML=html}
function renderShop(){if(!$("#shopList"))return;$("#shopList").innerHTML=state.shopping.length?state.shopping.map((s,i)=>`<div class="item"><h4>${s.item}</h4><p>${s.reason}</p><button class="secondary" onclick="state.shopping.splice(${i},1);save();render()">Remove</button></div>`).join(""):"<p>Shopping list empty.</p>"}
function renderRecipes(){if(!$("#recipeList"))return;$("#recipeList").innerHTML=state.recipes.length?state.recipes.map((r,i)=>`<div class="item"><h4>${r.title}</h4><p>${r.ingredients.map(x=>x.name).join(", ")}</p><button onclick="state.currentRecipe=state.recipes[${i}];showRecipe(state.currentRecipe)">Open</button></div>`).join(""):"<p>No recipes saved yet.</p>"}
function saveItem(){let item={name:$("#itemName").value.trim(),location:$("#itemLocation").value,qty:+$("#itemQty").value||0,unit:$("#itemUnit").value,yellow:+$("#itemYellow").value||0,red:+$("#itemRed").value||0,safety:$("#itemSafety").value,notes:$("#itemNotes").value.trim()};if(!item.name)return alert("Add item name first.");let ex=state.stock.find(x=>x.name.toLowerCase()===item.name.toLowerCase());ex?Object.assign(ex,item):state.stock.unshift(item);save();$("#itemName").value="";$("#itemNotes").value="";render();alert("Saved.")}
function adj(i,d){state.stock[i].qty=Math.max(0,+state.stock[i].qty+d);save();render()}function delStock(i){if(confirm("Delete item?")){state.stock.splice(i,1);save();render()}}
function generate(){let usable=state.stock.filter(i=>colour(i)!=="red"&&+i.qty>0);if(!usable.length)return alert("No usable stock.");let green=usable.filter(i=>colour(i)==="green"),amb=usable.filter(i=>colour(i)==="amber"),chosen=[...green.slice(0,5),...amb.slice(0,2)].slice(0,7),serv=+$("#recipeServings").value||2;let r={title:"Genevieve Stock-Safe "+$("#recipeStyle").value,created:new Date().toLocaleString(),servings:serv,notes:$("#recipeNotes").value,ingredients:chosen.map(i=>({name:i.name,qty:useQty(i,serv),unit:i.unit,colour:colour(i)})),steps:["Check labels before cooking.","Use green items first.","Review amber items carefully.","Do not use red or housemate food.","Cook simply and log symptoms if needed."]};state.currentRecipe=r;save();showRecipe(r)}
function useQty(i,s){let q=+i.qty;if(i.unit==="g"||i.unit==="ml")return Math.min(q,s*150);if(i.unit==="kg"||i.unit==="L")return Math.min(q,s*.25);return Math.min(q,s)}
function showRecipe(r){$("#recipeOutput").innerHTML=`<h4>${r.title}</h4><p>${r.notes||""}</p><ul>${r.ingredients.map(i=>`<li>${i.qty} ${i.unit} ${i.name} <span class="tag ${i.colour}">${i.colour}</span></li>`).join("")}</ul><ol>${r.steps.map(s=>`<li>${s}</li>`).join("")}</ol>`}
function deploy(){let r=state.currentRecipe;if(!r)return alert("Generate first.");r.ingredients.forEach(ing=>{let item=state.stock.find(x=>x.name===ing.name);if(item)item.qty=Math.max(0,+item.qty-+ing.qty)});state.usage.unshift({time:new Date().toISOString(),recipe:r.title,ingredients:r.ingredients.map(i=>`${i.qty} ${i.unit} ${i.name}`).join(" | ")});state.recipes.unshift(r);state.currentRecipe=null;save();render();alert("Recipe deployed. Stock lowered and shopping alerts updated.")}
function addShop(item,reason){if(item&&!state.shopping.some(x=>x.item.toLowerCase()===item.toLowerCase()))state.shopping.unshift({item,reason});save();render()}
function csv(rows,fields){let esc=v=>`"${String(v??"").replace(/"/g,'""')}"`;return [fields.join(","),...rows.map(r=>fields.map(f=>esc(r[f])).join(","))].join("\\n")}
function dl(name,text){let b=new Blob([text],{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();URL.revokeObjectURL(a.href)}
document.addEventListener("click",e=>{let s=e.target.closest("[data-screen]");if(s)go(s.dataset.screen);let f=e.target.closest("[data-filter]");if(f){state.filter=f.dataset.filter;$$("[data-filter]").forEach(b=>b.classList.remove("active"));f.classList.add("active");renderStock()}});
document.addEventListener("DOMContentLoaded",()=>{load();render();$("#saveItem").onclick=saveItem;$("#generateRecipe").onclick=generate;$("#deployRecipe").onclick=deploy;$("#saveRecipe").onclick=()=>{if(!state.currentRecipe)return alert("Generate first.");state.recipes.unshift(state.currentRecipe);state.currentRecipe=null;save();render();alert("Saved.")};$("#clearRecipe").onclick=()=>{$("#recipeOutput").innerHTML="<p>No recipe generated yet.</p>";state.currentRecipe=null;save()};$("#addShop").onclick=()=>{addShop($("#shopItem").value.trim(),$("#shopReason").value.trim()||"Manual");$("#shopItem").value="";$("#shopReason").value=""};$("#exportShopping").onclick=()=>dl("genevieve_v16_shopping.csv",csv(state.shopping,["item","reason"]));$("#exportStock").onclick=()=>dl("genevieve_v16_stock.csv",csv(state.stock,["name","location","qty","unit","yellow","red","safety","notes"]));$("#exportRecipes").onclick=()=>dl("genevieve_v16_recipes.csv",csv(state.recipes.map(r=>({created:r.created,title:r.title,servings:r.servings,ingredients:r.ingredients.map(i=>`${i.qty} ${i.unit} ${i.name}`).join(" | "),notes:r.notes})),["created","title","servings","ingredients","notes"]));$("#exportUsage").onclick=()=>dl("genevieve_v16_usage.csv",csv(state.usage,["time","recipe","ingredients"]))});